### ISSUE TITLE
Error in Install when run master.

### ISSUE THREAD

**Issue by halojoy** [ChrisBaines/DoveForums#15]
I can not get the master to work.
Has anybody?

========
A PHP Error was encountered

Severity: Warning

Message: mkdir(): Invalid path

Filename: drivers/Session_files_driver.php

Line Number: 117

Backtrace:

File: C:\Apache24\htdocs\doveforums\application\controllers\Install.php
Line: 19
Function: library

File: C:\Apache24\htdocs\doveforums\index.php
Line: 292
Function: require_once

**Comment by ChrisBaines** [comment]
Hello @halojoy,

I appologise for any problems you may be having with this.

I am currently investigating the issue, can you tell me what step in the process you are getting too before this error is shown?  

Also have you checked that the 'config' directory is writable? You need to maybe set the permissions to 777 just for the installer process, after this you can change them back to default.

Regards
Chris

**Comment by ChrisBaines** [comment]
Hi @halojoy,

I have just looked into this issue and I think i have located the problem, I will update the code shortly and this should fix the issue.

Regards
Chris

**Comment by ChrisBaines** [comment]
@halojoy,

I have just updated the 'master' branch with the bug fixes.  Please re-download and try again.  Hopefully this should have fixed the issue.

**Comment by halojoy** [comment]
That looks much better.
I come to the INSTALL page.
I have not installed yet. But I will.
I open a new issue if I find something bad.
