### ISSUE TITLE
You do not have permission to do that!.

### ISSUE THREAD

**Issue by axisdos** [ChrisBaines/DoveForums#17]
Hey there, just signed up on the forum. My username is daymond. Can you please activate my account. Thanks

**Comment by mirkobrombin** [comment]
From the code I see that only administrators can perform actions, I think for security reasons. Maybe in the next release :)

**Comment by axisdos** [comment]
Ok. Thanks

**Comment by ChrisBaines** [comment]
Hey @axisdos & @mirkobrombin,

I apologies for this, it is a bug in my code! ... I am pushing a update in a few minutes that will fix and address these issues.  I have overlooked some of the default settings that should be entered into the database at the time the site is installed.

Regards
Chris

**Comment by ChrisBaines** [comment]
Hey @axisdos & @mirkobrombin,

I have pushed a update and fixed my demo site, please register another account @axisdos as I had to clear out the users table to enable the correct permissions to be set.  

The Repo is now up to date and this bug has been cured.

Regards
Chris
