### ISSUE TITLE
Watch out for capital letter

### ISSUE THREAD

**Issue by Ragash** [ChrisBaines/DoveForums#2]
Hi! thanks for the amazing work!

i just tried to upload you repo to a webserver i have and noticed an error as soon i installed.

in wamp CI doesn't care about Capitalized letters in autoload but in linux it does.

so to let it run smootly i had to change in Application/Library:

MessageCI.php -> Messageci.php 

and in Models:

ion_auth_model.php -> Ion_auth_model.php

thanks for the great work and keep up!
Cheers
Mirko

**Comment by Ragash** [comment]
I noticed also MessageCI doesn't work propelly in linux enviroment:

it create the div with correct CSS styles but the content of them is also without Status Response text

**Comment by ChrisBaines** [comment]
Hi Ragash,  Thank you for pointing these errors out too me, i will take a look at the message CI library and try to figure out why its not working with the messages text, maybe something to do with the capitalisation on the language files ?

Im glad you like the work, keep watching as this week will see some big updates.

Regards
Chris

**Comment by Ragash** [comment]
found it!
it is a typo into the User controller.

into the register method you miscalled the:

lang(register_success) on line 183.

just change it to: lang(success_register...) and it will do ok.
same for the error_register.

then i noticed that for now lack an activation procedure, so i added this:

	//activate the user
	function activate($id, $code=false)
	{
		if ($code !== false)
		{
			$activation = $this->ion_auth->activate($id, $code);
		}
		else if ($this->ion_auth->is_admin())
		{
			$activation = $this->ion_auth->activate($id);
		}
		if ($activation)
		{
			// Create a message.
                $this->messageci->set( $this->ion_auth->messages(), 'success' );

                // Redirect.
                redirect( site_url('forums') );
		}
		else
		{			
			// Create a message.
			$this->messageci->set( $this->ion_auth->errors(), 'error' );
			
			// Redirect.
			redirect( site_url('forums') );
		}
	}

and obviusly you will need to change the config adeguatelly.
cheer up Chris! your work is amazing :)

**Comment by ChrisBaines** [comment]
Hi Ragash,

Brilliant, Thank you very much for helping with the contributions.  If you fork the Repo and then you can push your changes to it and I can merge them so that you get the credit =).

I will add this in now for you, I have pushed a few bug corrections to the repo this morning so you may want to pull down the updates and update your code as it effects the way categories and discussions are looped.

Thank you for the kind words =)

Chris

**Comment by ChrisBaines** [comment]
Hi Ragash,

I have pushed your updates and code and awarded credit where it is due =).

Chris
