### ISSUE TITLE
Installer not working

### ISSUE THREAD

**Issue by fbjerggaard** [ChrisBaines/DoveForums#20]
When cloning the repo as it stands right now, the installer doesn't work properly.

First of all - there might need to be set some rights on the different files that are written during the installation - these would be nice to have documented somewhere since as of right now the install script doesn't actually update the db info in the db config file.

Then the application/core/MY_Model is called MY_Model_Temp while it should have been MY_Model - perhaps it's not ready yet?

**Comment by fbjerggaard** [comment]
Creating the database.tmp file and giving the web-user write access to it seems to have fixed the issues. Might be worthy adding this to the readme :)

**Comment by ChrisBaines** [comment]
Hey @fbjerggaard,  Thank you for this feedback,  I have not yet seen this issue and i have run it on a number of local machines and some of my servers with no problems.

The MY_Model file is called MY_Model_Temp as Codeigniter will autoload it if not and this will cause problems with the installer.  

I am going to review the installer shortly and make it a bit smoother.

Thank you again for the feedback.

Regards
Chris

**Comment by mirkobrombin** [comment]
This look like a problem of file permissions.

**Comment by fbjerggaard** [comment]
@mirkobrombin - Also what I figured out, which I also wrote when I closed the issue :)

**Comment by mirkobrombin** [comment]
@fbjerggaard Have you another problem?

**Comment by fbjerggaard** [comment]
@mirkobrombin - Nope.
