### ISSUE TITLE
Install, but several keys to generate

### ISSUE THREAD

**Issue by halojoy** [ChrisBaines/DoveForums#21]
Installation went okay.
But then comes a page where you have to fill in 3-4 different keys.
I don't want to do this.
It is too complicated. I have to goto google.com to get keys.
I do not like it.

Well, this is why I have not Dove Forums at my site now.
I am sorry.

**Comment by ChrisBaines** [comment]
Hi @halojoy,

Thank you for the feedback.

The keys are for ReCaptcha to prevent spam and to stop bots signing up to the site to begin with.  This was a feature that was requested by other users. 

However maybe I have not tackled it the right way,  I will review the way I have implemented it and make it as a option that the administrator can turn on/off if they require it and remove theses steps from the installer.

I do apologies for your experience but I appreciate you giving it a try :+1: 

Regards 
Chris
