### ISSUE TITLE
Pagination does not work

### ISSUE THREAD

**Issue by ChrisBaines** [ChrisBaines/DoveForums#6]
Found a issue with the pagination today.

Changed comments_per_page setting to 2 and then added more than 2 comments to a discussion, when you click page 2, the page is not found.

**Comment by Ragash** [comment]
with only
$route['discussions/(:any)/(:any)'] = 'discussions/view/$1/$2';

you will view all the dicussion with comment <10, page 2 will give 404

with
$route['discussions/(:any)/(:any)/(:any)'] = 'discussions/view/$1/$2';

you will view only page 2, entering a discussion one page1 will give you 404
possible workaround:
$route['discussions/(:any)/(:any)'] = 'discussions/view/$1/$2';
$route['discussions/(:any)/(:any)/(:any)'] = 'discussions/view/$1/$2';


works as intended, even if it doesn't seem the proper way to make a routing rule :smile:
